version: '3'
services:
    grafana:
        image: 'grafana/grafana:latest'
        ports:
          - 3000:3000
        volumes:
          - ./src/grafana-board:/var/lib/grafana
    redis:
        image: 'redis:alpine'
        ports:
          - 6379:6379
    influxdb:
        image: 'influxdb:alpine'
        ports:
          - 8086:8086
        environment:
          - INFLUXDB_ADMIN_USER=admin
          - INFLUXDB_ADMIN_PASSWORD=admin
          - INFLUXDB_DB=metricsdatabase
          - INFLUXDB_USER=paymentgetway
          - INFLUXDB_USER_PASSWORD=paymentgetway
    bank-simulator:
        build: 
            dockerfile: Dockerfile
            context: ./src/bank-simulator
        hostname: bank-simulator
        ports:
          - 34765:80
    api:
        build: 
            dockerfile: Dockerfile
            context: ./src/payment-getway
        ports:
          - 5000:5000
        environment:
            - AcquiringBankConfiguration__BaseAddress=http://bank-simulator
            - RedisConnection=redis:6379,abortConnect=false
            - ApplicationMetrics__DataStore__Address=http://influxdb:8086
            - ApplicationMetrics__DataStore__Database=metricsdatabase
            - ApplicationMetrics__DataStore__UserName=paymentgetway
            - ApplicationMetrics__DataStore__Password=paymentgetway
            - ASPNETCORE_URLS=http://+:5000
        depends_on:
            - bank-simulator
            - influxdb
        
